sonar.projectKey=gelite-dev_gelite
sonar.organization=gelite-dev

sonar.sources=engine,tools
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.rust.lcov.reportPaths=target/llvm-cov/lcov.info

sonar.exclusions=target/**,Cargo.lock
