#![no_std]

//! SQL generation for SQLite schema application plans.
//!
//! This crate will render `sqlite_schema` plans into schema-management SQL such
//! as `CREATE TABLE`, `CREATE INDEX`, and engine metadata `INSERT` statements.
//!
//! It deliberately does not render runtime query SQL. SELECT statements and
//! later user-data DML are generated by `sqlite-sqlgen` from `sqlite-plan`.
//! This crate consumes schema-application plans from `sqlite-schema`.

#[cfg(test)]
mod tests;
