[package]
name = "gelite-commands"
version.workspace = true
edition.workspace = true

[dependencies]
chrono = { version = "0.4.45", default-features = false, features = ["std"] }
schema-model = { path = "../../engine/schema-model" }
schema-parser = { path = "../../engine/schema-parser" }
query-parser = { path = "../../engine/query-parser" }
query-ast = { path = "../../engine/query-ast" }
query-resolver = { path = "../../engine/query-resolver" }
sqlite-query-plan = { path = "../../engine/sqlite-query-plan" }
sqlite-query-sqlgen = { path = "../../engine/sqlite-query-sqlgen" }
sqlite-runner = { path = "../../engine/sqlite-runner" }
sqlite-schema-plan = { path = "../../engine/sqlite-schema-plan" }
sqlite-schema-sqlgen = { path = "../../engine/sqlite-schema-sqlgen" }
uuid = { version = "1.24.0", features = ["js", "v4"] }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
js-sys = "0.3.81"

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dev-dependencies]
sqlite-runner = { path = "../../engine/sqlite-runner", features = ["wasm"] }
wasm-bindgen-test = "0.3.54"
