#![no_std]
//! SQL generation for SQLite schema application plans.
//!
//! This crate will render `sqlite_schema` plans into schema-management SQL such
//! as `CREATE TABLE`, `CREATE INDEX`, and engine metadata `INSERT` statements.
//!
//! It deliberately does not render runtime query SQL. SELECT statements and
//! later user-data DML are generated by `sqlite-query-sqlgen` from `sqlite-query-plan`.
//! This crate consumes schema-application plans from `sqlite-schema-plan`.

extern crate alloc;
use alloc::format;
use alloc::string::{String, ToString};
use alloc::vec;
use alloc::vec::Vec;
use sqlite_schema_plan::{
    SQLiteAffinity, SQLiteColumnPlan, SQLiteForeignKeyPlan, SQLiteIndexPlan, SQLiteInsertPlan,
    SQLitePrimaryKeyPlan, SQLiteSchemaPlan, SQLiteTablePlan, SQLiteValuePlan,
    plan_catalog_field_inserts, plan_catalog_object_inserts,
};

pub fn render_create_table(table: &SQLiteTablePlan) -> String {
    let mut parts = vec![];

    parts.extend(table.columns().iter().map(render_column));

    if let Some(primary_key) = table.primary_key() {
        parts.push(render_primary_key(primary_key));
    }

    parts.extend(table.foreign_keys().iter().map(render_foreign_key));

    format!("CREATE TABLE {} ({})", table.name(), parts.join(", "))
}

fn render_column(column: &SQLiteColumnPlan) -> String {
    let mut parts: Vec<String> = Vec::new();

    parts.push(column.name().to_string());
    parts.push(render_affinity(column.affinity()).to_string());

    if column.is_nullable() {
        parts.push("NULL".to_string());
    } else {
        parts.push("NOT NULL".to_string());
    }

    if column.is_primary_key() {
        parts.push("PRIMARY KEY".to_string());
    }

    if column.is_unique() {
        parts.push("UNIQUE".to_string());
    }

    parts.join(" ")
}

fn render_affinity(affinity: SQLiteAffinity) -> &'static str {
    match affinity {
        SQLiteAffinity::Integer => "INTEGER",
        SQLiteAffinity::Real => "REAL",
        SQLiteAffinity::Text => "TEXT",
    }
}

fn render_primary_key(primary_key: &SQLitePrimaryKeyPlan) -> String {
    format!("PRIMARY KEY ({})", primary_key.column_names().join(", "))
}

fn render_foreign_key(foreign_key: &SQLiteForeignKeyPlan) -> String {
    format!(
        "FOREIGN KEY ({}) REFERENCES {}({})",
        foreign_key.column_name(),
        foreign_key.target_table(),
        foreign_key.target_column(),
    )
}

pub fn render_create_index(index: &SQLiteIndexPlan) -> String {
    let create = if index.is_unique() {
        "CREATE UNIQUE INDEX"
    } else {
        "CREATE INDEX"
    };

    format!(
        "{} {} ON {} ({})",
        create,
        index.name(),
        index.table_name(),
        index.column_names().join(", "),
    )
}

pub struct RenderedInsert {
    sql: String,
    values: Vec<SQLiteValuePlan>,
}

impl RenderedInsert {
    pub fn sql(&self) -> &str {
        &self.sql
    }
    pub fn values(&self) -> &[SQLiteValuePlan] {
        &self.values
    }
}

pub fn render_insert(insert: &SQLiteInsertPlan) -> RenderedInsert {
    let columns = insert.columns().join(", ");
    let placeholders = insert
        .columns()
        .iter()
        .map(|_| "?")
        .collect::<Vec<_>>()
        .join(", ");

    RenderedInsert {
        sql: format!(
            "INSERT INTO {} ({}) VALUES ({})",
            insert.table_name(),
            columns,
            placeholders,
        ),
        values: insert.values().to_vec(),
    }
}

pub enum RenderedSchemaStatement {
    Sql(String),
    Insert(RenderedInsert),
}

impl RenderedSchemaStatement {
    pub fn sql(&self) -> &str {
        match self {
            Self::Sql(sql) => sql,
            Self::Insert(insert) => insert.sql(),
        }
    }
}

pub fn render_initial_schema(plan: &SQLiteSchemaPlan) -> Vec<RenderedSchemaStatement> {
    let mut statements = Vec::new();

    statements.extend(
        plan.metadata_tables()
            .iter()
            .map(render_create_table)
            .map(RenderedSchemaStatement::Sql),
    );
    statements.extend(
        plan.object_tables()
            .iter()
            .map(render_create_table)
            .map(RenderedSchemaStatement::Sql),
    );
    statements.extend(
        plan.relation_tables()
            .iter()
            .map(render_create_table)
            .map(RenderedSchemaStatement::Sql),
    );
    statements.extend(
        plan_catalog_object_inserts(plan)
            .iter()
            .map(render_insert)
            .map(RenderedSchemaStatement::Insert),
    );
    statements.extend(
        plan_catalog_field_inserts(plan)
            .iter()
            .map(render_insert)
            .map(RenderedSchemaStatement::Insert),
    );
    statements.extend(
        plan.indexes()
            .iter()
            .map(render_create_index)
            .map(RenderedSchemaStatement::Sql),
    );

    statements
}

#[cfg(test)]
mod tests;
